export const YEAR_MIN = -250;
export const YEAR_MAX = 2026;

export const MOMENTS = [
  {
    year: -250,
    icon: "🛖",
    titre: "Lutèce des Parisii",
    recit: "Il y a très très longtemps, Paris n'existe pas encore ! Une tribu gauloise, les Parisii, vit sur une petite île au milieu du fleuve. Autour, il n'y a que des forêts, des marais et des animaux sauvages.",
    population: 1000,
    chezNous: "Chez toi ? Une grande forêt où courent les sangliers !",
  },
  {
    year: 200,
    icon: "🏛️",
    titre: "Lutèce la romaine",
    recit: "Les Romains ont gagné la guerre et la ville s'appelle Lutèce. Ils construisent en pierre : un forum, des thermes pour se laver, et de grandes arènes pour les spectacles.",
    population: 10000,
    chezNous: "Chez toi, c'est toujours la pleine campagne.",
  },
  {
    year: 885,
    icon: "⚔️",
    titre: "Le siège des Vikings",
    recit: "Des Vikings remontent la Seine sur leurs drakkars pour attaquer Paris ! Les Parisiens se réfugient sur l'île, derrière les remparts, et résistent pendant des mois. La ville tiendra bon.",
    population: 20000,
    chezNous: "De chez toi, on verrait la fumée au loin…",
  },
  {
    year: 1200,
    icon: "🏰",
    titre: "La muraille de Philippe Auguste",
    recit: "Le roi Philippe Auguste construit une grande muraille tout autour de Paris, et un château fort : le Louvre. Sur l'île, on bâtit une cathédrale immense, Notre-Dame — le chantier durera presque 200 ans !",
    population: 50000,
    chezNous: "Chez toi poussent des vignes et des moulins à vent.",
  },
  {
    year: 1370,
    icon: "🛡️",
    titre: "Charles V et la Bastille",
    recit: "Paris a tellement grandi qu'il déborde de la vieille muraille ! Le roi Charles V en construit une nouvelle, plus grande, gardée par une énorme forteresse à huit tours : la Bastille.",
    population: 250000,
    chezNous: "Ton quartier est un petit village, loin des remparts.",
  },
  {
    year: 1670,
    icon: "🌳",
    titre: "La ville ouverte",
    recit: "Louis XIV, le Roi-Soleil, se sent si fort qu'il fait démolir les remparts ! À leur place, on plante des arbres et on se promène : ce sont les Grands Boulevards. Paris devient une ville ouverte.",
    population: 500000,
    chezNous: "Ton village s'appelle Clignancourt, et on y cultive des champs.",
  },
  {
    year: 1789,
    icon: "🔥",
    titre: "La Révolution",
    recit: "C'est la Révolution ! Le peuple de Paris prend la Bastille, la prison du roi, puis la démonte pierre par pierre. Il n'en reste rien — aujourd'hui, c'est une place avec une colonne dorée.",
    population: 650000,
    chezNous: "Chez toi, on entend gronder Paris tout proche.",
  },
  {
    year: 1860,
    icon: "🚂",
    titre: "Ton quartier devient Paris",
    recit: "Paris avale d'un coup tous les villages qui l'entourent — et le tien aussi : ton quartier devient Paris ! Un petit train, la petite ceinture, fait le tour de la ville. Il passe tout près de chez toi.",
    population: 1700000,
    chezNous: "Bienvenue à Paris, 18e arrondissement !",
  },
  {
    year: 1865,
    icon: "🏗️",
    titre: "Haussmann transforme tout",
    recit: "Le baron Haussmann transforme tout : il perce de grandes avenues bien droites et construit des milliers d'immeubles en pierre claire, aux toits gris en zinc. C'est le Paris qu'on connaît aujourd'hui !",
    population: 1800000,
    chezNous: "Ta rue à toi sera percée quelques années plus tard.",
  },
  {
    year: 1889,
    icon: "🗼",
    titre: "La Tour Eiffel",
    recit: "Tu la vois depuis le début en fantôme… la voilà pour de vrai ! Gustave Eiffel construit la tour la plus haute du monde : 300 mètres ! Certains la trouvent affreuse — aujourd'hui, c'est la star de Paris.",
    population: 2300000,
    chezNous: "De ta butte, on la voit briller à l'autre bout de la ville.",
  },
  {
    year: 1900,
    icon: "🚇",
    titre: "Le métro",
    recit: "Paris creuse un train sous la terre : le métro ! La première ligne ouvre pour l'Exposition universelle. Bientôt, près de chez toi, il roulera même en l'air, sur un grand pont au-dessus du boulevard.",
    population: 2700000,
    chezNous: "Ta station arrivera en 1912 : Porte de Saint-Ouen.",
  },
  {
    year: 1934,
    icon: "🌿",
    titre: "La petite ceinture s'endort",
    recit: "La petite ceinture s'arrête : plus personne ne prend le petit train, tout le monde préfère le métro. Les rails restent là, tout tranquilles, et petit à petit les herbes et les arbres poussent dessus.",
    population: 2900000,
    chezNous: "Le petit train ne siffle plus au bout de ta rue.",
  },
  {
    year: 1973,
    icon: "🚗",
    titre: "Le périphérique",
    recit: "Une rivière de voitures encercle Paris : le périphérique ! Il est construit pile là où se trouvait la dernière muraille. Il passe à deux pas de chez toi — écoute, on l'entend presque.",
    population: 2300000,
    chezNous: "Ta maison est juste entre les rails endormis et le périph.",
  },
  {
    year: 2026,
    icon: "🌍",
    titre: "Ton Paris",
    recit: "Voici ton Paris ! La petite ceinture est devenue un jardin sauvage, on replante des arbres partout, et au loin brillent les tours de La Défense. Deux mille ans d'histoire — et toi, tu habites dedans.",
    population: 2100000,
    chezNous: "Et l'histoire continue avec toi.",
  },
];
